import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "./_components/sidebar";
import { Header } from "./_components/header";
import { headers } from "next/headers";
import { getSession } from "@/actions/session";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = headers();
  const path =
    (await headersList).get("x-pathname") || (await headersList).get("x-url");
  const isLoginPage = path?.includes("/login");
  const session = await getSession();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col bg-neutral-50`}
      >
        <Sidebar role={session?.role} username={session?.username} />
        <div
          className={`min-h-screen flex-1 flex flex-col transition-all duration-300 ${
            !isLoginPage ? "lg:pl-72" : ""
          }`}
        >
          <Header notificationCount={1} username={session?.username} />
          <main className={`${isLoginPage ? "" : "p-4 md:p-6"} flex-1`}>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
