-- AlterTable
ALTER TABLE `hasil_clustering` ADD COLUMN `agustus` INTEGER NULL,
    ADD COLUMN `april` INTEGER NULL,
    ADD COLUMN `centroid_agustus` DOUBLE NULL,
    ADD COLUMN `centroid_april` DOUBLE NULL,
    ADD COLUMN `centroid_desember` DOUBLE NULL,
    ADD COLUMN `centroid_juli` DOUBLE NULL,
    ADD COLUMN `centroid_juni` DOUBLE NULL,
    ADD COLUMN `centroid_mei` DOUBLE NULL,
    ADD COLUMN `centroid_november` DOUBLE NULL,
    ADD COLUMN `centroid_oktober` DOUBLE NULL,
    ADD COLUMN `centroid_september` DOUBLE NULL,
    ADD COLUMN `desember` INTEGER NULL,
    ADD COLUMN `juli` INTEGER NULL,
    ADD COLUMN `juni` INTEGER NULL,
    ADD COLUMN `mei` INTEGER NULL,
    ADD COLUMN `november` INTEGER NULL,
    ADD COLUMN `oktober` INTEGER NULL,
    ADD COLUMN `september` INTEGER NULL,
    MODIFY `januari` INTEGER NULL,
    MODIFY `februari` INTEGER NULL,
    MODIFY `maret` INTEGER NULL,
    MODIFY `centroid_februari` DOUBLE NULL,
    MODIFY `centroid_januari` DOUBLE NULL,
    MODIFY `centroid_maret` DOUBLE NULL;
